version: '3'

services:
  postgres:
    container_name: postgres_db
    image: postgres:13
    restart: always
    env_file:
      - .env
    expose:
      - "5432"
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data

  django:
    container_name: django
    build:
      context: web
    volumes:
      - static_data:/app/static
    env_file:
      - .env
    depends_on:
      - postgres

  nginx:
    container_name: nginx
    build:
      context: ./nginx
    volumes:
      - static_data:/static
    ports:
      - "90:80"
    depends_on:
      - django
#      - fast_api

  elasticsearch:
    container_name: elastic_search
    image: elasticsearch:7.17.1
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    env_file:
      - .env

  redis:
    container_name: redis
    image: redis:7.0-alpine
    command:
      - redis-server

  etl:
    container_name: etl
    build:
      context: etl
    env_file:
      - ./etl/app/.env
    depends_on:
      - elasticsearch
      - postgres
      - redis

  fast_api:
    container_name: fast_api
    build:
      context: fast_api
    image: fastapi_image
#    ports:
#      - "8000:8000"
    depends_on:
      - elasticsearch
      - redis

#  tests:
#    container_name: tests
#    image: fastapi_image
#    depends_on:
#      - elasticsearch
#      - redis
#    entrypoint: >
#      sh -c "pip install -r /tests/functional/requirements.txt
#      && python3 /tests/functional/utils/wait_for_es.py
#      && python3 /tests/functional/utils/wait_for_redis.py
#      && pytest /tests/functional/src"

volumes:
  static_data:
